- name: Install wireless drivers
  become: yes
  package:
    name: broadcom-wl
    state: present

- name: Change hostname
  hostname:
    name: "pi-desktop"

- name: Edit /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost pi-desktop'
    state: present
