- name: Enable sshd
  become: yes
  ansible.builtin.service:
    name: sshd
    enabled: yes

- name: Enable libvirtd
  become: yes
  ansible.builtin.service:
    name: libvirtd
    enabled: yes

- name: Install syncthing
  become: yes
  package:
    name: syncthing
    state: present
- name: Enable syncthing
  become: yes
  ansible.builtin.service:
    name: syncthing@ap
    enabled: yes
